source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Sphinx_Example' do
    pod 'Sphinx', :path => '../', :configuation => 'DEBUG'
    pod 'Masonry', '~> 1.1.0'
end
